CREATE TABLE SEQUENCES (
  ID           VARCHAR(36)      NOT NULL PRIMARY KEY,
  NAME         NVARCHAR(200)    NOT NULL,
  OWNER_UID    NVARCHAR(128)    NOT NULL,
  FLOW_JSON    NCLOB            NOT NULL,
  STATUS       VARCHAR(20)      DEFAULT 'draft',
  CREATED_AT   TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT   TIMESTAMP        DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_SEQUENCES_OWNER ON SEQUENCES (OWNER_UID);
