CREATE TABLE SEQUENCE_ENROLLMENTS (
  ID             VARCHAR(36)    NOT NULL PRIMARY KEY,
  SEQUENCE_ID    VARCHAR(36)    NOT NULL,
  EMAIL_ADDRESS  NVARCHAR(254)  NOT NULL,
  CURRENT_NODE   VARCHAR(36)    NOT NULL,
  STATUS         VARCHAR(20)    DEFAULT 'active',
  NEXT_RUN_AT    TIMESTAMP      NOT NULL,
  LAST_BATCH_ID  VARCHAR(50),
  METADATA       NCLOB,
  CREATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_SE_NEXT_RUN ON SEQUENCE_ENROLLMENTS (NEXT_RUN_AT, STATUS);
CREATE INDEX IDX_SE_SEQUENCE  ON SEQUENCE_ENROLLMENTS (SEQUENCE_ID);
CREATE INDEX IDX_SE_EMAIL     ON SEQUENCE_ENROLLMENTS (EMAIL_ADDRESS, SEQUENCE_ID);
